### ISSUE TITLE
Change Repo name and URL on Heroku

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/travelx#73]
- [x] Change repo name
- [x] Change URL on Heroku

**Comment by arun-esh** [comment]
New URL: https://app-travelx.herokuapp.com/

**Comment by arun-esh** [comment]
@jalpa015 any concerns?? should I close the issue?

**Comment by jalpa015** [comment]
@arun-esh That looks perfect to me. I feel we can close this issue now.
