### ISSUE TITLE
Create Test cases for CI deployment

### ISSUE THREAD

**Issue by jalpa015** [arun-esh/travelx#81]
Create test cases to be checked before CI deployment. 

Suggestions - Mocha is one such package that can be helpful for creating tests

**Comment by arun-esh** [comment]
@jalpa015 I would like to take on this task. Would you able to provide some assistance?

**Comment by jalpa015** [comment]
@arun-esh 

Basic steps to testing - https://www.freecodecamp.org/news/how-to-start-unit-testing-javascript/
js has frameworks now. Mocha, jest are examples of testing frameworks
